List<Map<String, String>> quote = [
  {"Quotes": "Be yourself; everyone else is already taken.", "Auth": "Oscar Wilde"},
  {"Quotes": "I'm not afraid of death; I just don't want to be there when it happens.", "Auth": "Woody Allen"},
  {"Quotes": "So many books, so little time.", "Auth": "Frank Zappa"},
  {"Quotes": "A room without books is like a body without a soul.", "Auth": "Marcus Tullius Cicero"},
  {"Quotes": "In three words I can sum up everything I've learned about life: it goes on.", "Auth": "Robert Frost"},
  {"Quotes": "If you tell the truth, you don't have to remember anything.", "Auth": "Mark Twain"},
  {"Quotes": "A friend is someone who knows all about you and still loves you.", "Auth": "Elbert Hubbard"},
  {"Quotes": "To live is the rarest thing in the world. Most people exist, that is all.", "Auth": "Oscar Wilde"},
  {"Quotes": "Without music, life would be a mistake.", "Auth": "Friedrich Nietzsche"},
  {"Quotes": "We accept the love we think we deserve.", "Auth": "Stephen Chbosky"},

  {"Quotes": "It is never too late to be what you might have been.", "Auth": "George Eliot"},
  {"Quotes": "Everything you can imagine is real.", "Auth": "Pablo Picasso"},
  {"Quotes": "Do what you can, with what you have, where you are.", "Auth": "Theodore Roosevelt"},
  {"Quotes": "Success is not final, failure is not fatal: it is the courage to continue that counts.", "Auth": "Winston Churchill"},
  {"Quotes": "Turn your wounds into wisdom.", "Auth": "Oprah Winfrey"},
  {"Quotes": "The purpose of our lives is to be happy.", "Auth": "Dalai Lama"},
  {"Quotes": "Get busy living or get busy dying.", "Auth": "Stephen King"},
  {"Quotes": "You only live once, but if you do it right, once is enough.", "Auth": "Mae West"},
  {"Quotes": "Many of life’s failures are people who did not realize how close they were to success when they gave up.", "Auth": "Thomas Edison"},
  {"Quotes": "If life were predictable it would cease to be life.", "Auth": "Eleanor Roosevelt"},

  {"Quotes": "Life is what happens when you're busy making other plans.", "Auth": "John Lennon"},
  {"Quotes": "Spread love everywhere you go.", "Auth": "Mother Teresa"},
  {"Quotes": "When you reach the end of your rope, tie a knot in it and hang on.", "Auth": "Franklin D. Roosevelt"},
  {"Quotes": "Always remember that you are absolutely unique.", "Auth": "Margaret Mead"},
  {"Quotes": "Don't judge each day by the harvest you reap but by the seeds that you plant.", "Auth": "Robert Louis Stevenson"},
  {"Quotes": "The future belongs to those who believe in the beauty of their dreams.", "Auth": "Eleanor Roosevelt"},
  {"Quotes": "Tell me and I forget. Teach me and I remember. Involve me and I learn.", "Auth": "Benjamin Franklin"},
  {"Quotes": "The best and most beautiful things in the world cannot be seen or even touched.", "Auth": "Helen Keller"},
  {"Quotes": "It does not matter how slowly you go as long as you do not stop.", "Auth": "Confucius"},
  {"Quotes": "Everything has beauty, but not everyone sees it.", "Auth": "Confucius"},

  {"Quotes": "Believe you can and you're halfway there.", "Auth": "Theodore Roosevelt"},
  {"Quotes": "The only impossible journey is the one you never begin.", "Auth": "Tony Robbins"},
  {"Quotes": "Go confidently in the direction of your dreams.", "Auth": "Henry David Thoreau"},
  {"Quotes": "Dream big and dare to fail.", "Auth": "Norman Vaughan"},
  {"Quotes": "Act as if what you do makes a difference. It does.", "Auth": "William James"},
  {"Quotes": "Success usually comes to those who are too busy to be looking for it.", "Auth": "Henry David Thoreau"},
  {"Quotes": "Don't watch the clock; do what it does. Keep going.", "Auth": "Sam Levenson"},
  {"Quotes": "Keep your face always toward the sunshine—and shadows will fall behind you.", "Auth": "Walt Whitman"},
  {"Quotes": "Opportunities don't happen. You create them.", "Auth": "Chris Grosser"},
  {"Quotes": "Try not to become a man of success, but rather become a man of value.", "Auth": "Albert Einstein"},

  {"Quotes": "The only limit to our realization of tomorrow is our doubts of today.", "Auth": "Franklin D. Roosevelt"},
  {"Quotes": "Do one thing every day that scares you.", "Auth": "Eleanor Roosevelt"},
  {"Quotes": "It always seems impossible until it's done.", "Auth": "Nelson Mandela"},
  {"Quotes": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Auth": "Ralph Waldo Emerson"},
  {"Quotes": "Happiness depends upon ourselves.", "Auth": "Aristotle"},
  {"Quotes": "Turn your face to the sun and the shadows fall behind you.", "Auth": "Maori Proverb"},
  {"Quotes": "The journey of a thousand miles begins with one step.", "Auth": "Lao Tzu"},
  {"Quotes": "That which does not kill us makes us stronger.", "Auth": "Friedrich Nietzsche"},
  {"Quotes": "Strive not to be a success, but rather to be of value.", "Auth": "Albert Einstein"},
  {"Quotes": "The best way to predict your future is to create it.", "Auth": "Abraham Lincoln"},

  {"Quotes": "An unexamined life is not worth living.", "Auth": "Socrates"},
  {"Quotes": "Eighty percent of success is showing up.", "Auth": "Woody Allen"},
  {"Quotes": "Your time is limited, don't waste it living someone else's life.", "Auth": "Steve Jobs"},
  {"Quotes": "Winning isn't everything, but wanting to win is.", "Auth": "Vince Lombardi"},
  {"Quotes": "I am not a product of my circumstances. I am a product of my decisions.", "Auth": "Stephen Covey"},
  {"Quotes": "Every strike brings me closer to the next home run.", "Auth": "Babe Ruth"},
  {"Quotes": "Life is 10% what happens to me and 90% of how I react to it.", "Auth": "Charles Swindoll"},
  {"Quotes": "The mind is everything. What you think you become.", "Auth": "Buddha"},
  {"Quotes": "The best revenge is massive success.", "Auth": "Frank Sinatra"},
  {"Quotes": "Your life does not get better by chance, it gets better by change.", "Auth": "Jim Rohn"},

  {"Quotes": "You miss 100% of the shots you don’t take.", "Auth": "Wayne Gretzky"},
  {"Quotes": "Whether you think you can or you think you can’t, you’re right.", "Auth": "Henry Ford"},
  {"Quotes": "I have not failed. I've just found 10,000 ways that won't work.", "Auth": "Thomas Edison"},
  {"Quotes": "A person who never made a mistake never tried anything new.", "Auth": "Albert Einstein"},
  {"Quotes": "The only way to do great work is to love what you do.", "Auth": "Steve Jobs"},
  {"Quotes": "If you can dream it, you can achieve it.", "Auth": "Zig Ziglar"},
  {"Quotes": "Do what you feel in your heart to be right.", "Auth": "Eleanor Roosevelt"},
  {"Quotes": "Hardships often prepare ordinary people for an extraordinary destiny.", "Auth": "C.S. Lewis"},
  {"Quotes": "Believe in yourself and all that you are.", "Auth": "Christian D. Larson"},
  {"Quotes": "What we think, we become.", "Auth": "Buddha"},

  {"Quotes": "Start where you are. Use what you have. Do what you can.", "Auth": "Arthur Ashe"},
  {"Quotes": "If opportunity doesn't knock, build a door.", "Auth": "Milton Berle"},
  {"Quotes": "Quality is not an act, it is a habit.", "Auth": "Aristotle"},
  {"Quotes": "With the new day comes new strength and new thoughts.", "Auth": "Eleanor Roosevelt"},
  {"Quotes": "The secret of getting ahead is getting started.", "Auth": "Mark Twain"},
  {"Quotes": "Well done is better than well said.", "Auth": "Benjamin Franklin"},
  {"Quotes": "If you want to lift yourself up, lift up someone else.", "Auth": "Booker T. Washington"},
  {"Quotes": "Knowing yourself is the beginning of all wisdom.", "Auth": "Aristotle"},
  {"Quotes": "The harder I work, the luckier I get.", "Auth": "Gary Player"},
  {"Quotes": "Dream as if you'll live forever. Live as if you'll die today.", "Auth": "James Dean"},

  {"Quotes": "It is during our darkest moments that we must focus to see the light.", "Auth": "Aristotle"},
  {"Quotes": "Don't wait. The time will never be just right.", "Auth": "Napoleon Hill"},
  {"Quotes": "Everything you’ve ever wanted is on the other side of fear.", "Auth": "George Addair"},
  {"Quotes": "Do what you love and the money will follow.", "Auth": "Marsha Sinetar"},
  {"Quotes": "You become what you believe.", "Auth": "Oprah Winfrey"},
  {"Quotes": "Success is walking from failure to failure with no loss of enthusiasm.", "Auth": "Winston Churchill"},
  {"Quotes": "Fall seven times and stand up eight.", "Auth": "Japanese Proverb"},
  {"Quotes": "Happiness is not something ready made. It comes from your own actions.", "Auth": "Dalai Lama"},
  {"Quotes": "If you’re going through hell, keep going.", "Auth": "Winston Churchill"},
  {"Quotes": "Limit your 'always' and your 'nevers'.", "Auth": "Amy Poehler"},
];